### ISSUE TITLE
[Bug] Error: Set OpenAI Key in OPENAI_API_KEY env variable

### ISSUE THREAD

**Issue by swamichandra** [run-llama/chat-llamaindex#23]
Trying to generate a new data source and when I run `pnpm run generate <datasource-name>` get the following error. The OpenAI key is set in .env.development.local. The app works, but not the data source generation.

```
chat-llamaindex\node_modules\.pnpm\llamaindex@0.0.0-20231018030303_encoding@0.1.13\node_modules\llamaindex\dist\index.js:470
      throw new Error("Set OpenAI Key in OPENAI_API_KEY env variable");
            ^
Error: Set OpenAI Key in OPENAI_API_KEY env variable
    at new OpenAISession (~\WORKSPACES\GenerativeAI\chat-llamaindex\node_modules\.pnpm\llamaindex@0.0.0-20231018030303_encoding@0.1.13\node_modules\llamaindex\dist\index.js:470:13)
    at getOpenAISession (~\Documents\WORKSPACES\GenerativeAI\chat-llamaindex\node_modules\.pnpm\llamaindex@0.0.0-20231018030303_encoding@0.1.13\node_modules\llamaindex\dist\index.js:486:15)
    at new OpenAI2 (~\Documents\WORKSPACES\GenerativeAI\chat-llamaindex\node_modules\.pnpm\llamaindex@0.0.0-20231018030303_encoding@0.1.13\node_modules\llamaindex\dist\index.js:606:81)
    at serviceContextFromDefaults (~\Documents\WORKSPACES\GenerativeAI\chat-llamaindex\node_modules\.pnpm\llamaindex@0.0.0-20231018030303_encoding@0.1.13\node_modules\llamaindex\dist\index.js:2075:71)
    at file:///~/Documents/WORKSPACES/GenerativeAI/chat-llamaindex/scripts/generate.mjs:54:26
    at file:///~/Documents/WORKSPACES/GenerativeAI/chat-llamaindex/scripts/generate.mjs:61:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by marcusschiesser** [comment]
Thanks for finding this. It's fixed in this commit: https://github.com/run-llama/chat-llamaindex/commit/78b3af869aeea9a90daf29e696d4acce9650ba93
